ProyectoFinal/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoFinal.Context;
using ProyectoFinal.Models;

namespace ProyectoFinal.Controllers
{
    public class CategoriesController : Controller
    {
        private ProyectoFinalDbContext db = new ProyectoFinalDbContext();

        // GET: Categories
        public async Task<ActionResult> Index()
        {
            return View(await db.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = await db.Categories.FindAsync(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "CategoryKey,CotegoryName,CategoryDescription")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = await db.Categories.FindAsync(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "CategoryKey,CotegoryName,CategoryDescription")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = await db.Categories.FindAsync(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Category category = await db.Categories.FindAsync(id);
            db.Categories.Remove(category);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoFinal/Controllers/FormaPagoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoFinal.Context;
using ProyectoFinal.Models;

namespace ProyectoFinal.Controllers
{
    public class FormaPagoesController : Controller
    {
        private ProyectoFinalDbContext db = new ProyectoFinalDbContext();

        // GET: FormaPagoes
        public async Task<ActionResult> Index()
        {
            return View(await db.FormaPagoes.ToListAsync());
        }

        // GET: FormaPagoes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FormaPago formaPago = await db.FormaPagoes.FindAsync(id);
            if (formaPago == null)
            {
                return HttpNotFound();
            }
            return View(formaPago);
        }

        // GET: FormaPagoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FormaPagoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "FormaPagoId,FormaPagoNombre")] FormaPago formaPago)
        {
            if (ModelState.IsValid)
            {
                db.FormaPagoes.Add(formaPago);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(formaPago);
        }

        // GET: FormaPagoes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FormaPago formaPago = await db.FormaPagoes.FindAsync(id);
            if (formaPago == null)
            {
                return HttpNotFound();
            }
            return View(formaPago);
        }

        // POST: FormaPagoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "FormaPagoId,FormaPagoNombre")] FormaPago formaPago)
        {
            if (ModelState.IsValid)
            {
                db.Entry(formaPago).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(formaPago);
        }

        // GET: FormaPagoes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FormaPago formaPago = await db.FormaPagoes.FindAsync(id);
            if (formaPago == null)
            {
                return HttpNotFound();
            }
            return View(formaPago);
        }

        // POST: FormaPagoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            FormaPago formaPago = await db.FormaPagoes.FindAsync(id);
            db.FormaPagoes.Remove(formaPago);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoFinal/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoFinal.Context;
using ProyectoFinal.Models;
using Microsoft.AspNet.Identity;
using ProyectoFinal.Models.ViewModels;
using System.Data.Entity.Migrations;
using System.Web.Http.Results;

namespace ProyectoFinal.Controllers
{
    public class PedidosController : Controller
    {
        private ProyectoFinalDbContext db = new ProyectoFinalDbContext();

        // GET: Pedidos
        public async Task<ActionResult> Index()
        {
            string usuario = null;
            if (User.Identity.IsAuthenticated)
            {
                usuario = User.Identity.GetUserId();
            }
            else
            {
                if (Session["UniqueIdUserAnonimo"] == null)
                {
                    usuario = Guid.NewGuid().ToString();
                    Session["UniqueIdUserAnonimo"] = usuario;
                }
                else
                {
                    usuario = (string)Session["UniqueIdUserAnonimo"];
                }


            }
            return View(await db.Pedidos.Where(p => p.UsuarioId == usuario).ToListAsync());
        }

        // GET: Pedidos/Details/5
        public ActionResult Details()
        {
            string usuario = null;
            if (User.Identity.IsAuthenticated)
            {
                usuario = User.Identity.GetUserId();
            }
            else
            {
                if (Session["UniqueIdUserAnonimo"] == null)
                {
                    usuario = Guid.NewGuid().ToString();
                    Session["UniqueIdUserAnonimo"] = usuario;
                }
                else
                {
                    usuario = (string)Session["UniqueIdUserAnonimo"];
                }


            }
            ViewBag.FormaPagoId = new SelectList(db.FormaPagoes, "FormaPagoId", "FormaPagoNombre");
            var carrito = db.Carritoes.Include(c => c.Producto).Where(x => x.UsuarioId == usuario).ToList();
            var view = new PedidosViewModel();
            view.carrito = carrito;
            return View(view);
        }


        // POST: Pedidos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(PedidosViewModel model)
        {
            string usuario = null;
            if (User.Identity.IsAuthenticated)
            {
                usuario = User.Identity.GetUserId();
            }
            else
            {
                if (Session["UniqueIdUserAnonimo"] == null)
                {
                    usuario = Guid.NewGuid().ToString();
                    Session["UniqueIdUserAnonimo"] = usuario;
                }
                else
                {
                    usuario = (string)Session["UniqueIdUserAnonimo"];
                }


            }

            var carritoUsuario = db.Carritoes.Include(c => c.Producto).Where(x => x.UsuarioId == usuario);
            decimal total = 0;
            foreach (var item in carritoUsuario)
            {
                total += (decimal.Parse(item.CarritoCantidad.ToString()) * item.Producto.ProductoPrecio);
            }

            var pedido = new Pedidos
            {

                Nombres = model.Nombres,
                Apellidos = model.Apellidos,
                Email = model.Email,
                Telefono = model.Telefono,
                UsuarioId = usuario,
                EstadoPedido = 1,
                FormaPagoId = model.FormaPagoId,
                PedidoDireccion = model.PedidoDireccion,
                PedidoFecha = DateTime.Now,
                TotalPedido = total
            };
            db.Pedidos.Add(pedido);
            await db.SaveChangesAsync();

            await saveDetalleAsync(usuario, carritoUsuario, pedido.PedidoId);

            return RedirectToAction("Index");
        }

        private async Task saveDetalleAsync(string usuario, IQueryable<Carrito> model, int id)
        {
            // se usan transacciones para poder realizar varios cambios a la db al mismo tiempo4
            using (var dbTran = db.Database.BeginTransaction())
            {
                try
                {
                    foreach (var item in model)
                    {
                        var detalle = new DetallePedido
                        {
                            DetalleProductoCantidad = item.CarritoCantidad,
                            ProductoId = item.IdProducto,
                            PedidoId = id
                        };
                        //guarda el detalle
                        db.Set<DetallePedido>().AddOrUpdate(detalle);
                        await db.SaveChangesAsync();

                        //borrar el carrito
                        db.Set<Carrito>().Remove(item);
                        await db.SaveChangesAsync();

                    }
                    dbTran.Commit();
                }
                catch (Exception)
                {
                    // roll back all database operations, if any thing goes wrong
                    dbTran.Rollback();
                }
            }
        }


        public ActionResult Items(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            string usuario = null;
            if (User.Identity.IsAuthenticated)
            {
                usuario = User.Identity.GetUserId();
            }
            else
            {
                if (Session["UniqueIdUserAnonimo"] == null)
                {
                    usuario = Guid.NewGuid().ToString();
                    Session["UniqueIdUserAnonimo"] = usuario;
                }
                else
                {
                    usuario = (string)Session["UniqueIdUserAnonimo"];
                }


            }

            var datosPedido = db.Pedidos.Include(p => p.FormaPago).Where(p => p.PedidoId == id).FirstOrDefault();
            var pedido = new DetalleCompraViewModel { 
                PedidoId = datosPedido.PedidoId,
                Nombres = datosPedido.Nombres,
                Apellidos = datosPedido.Apellidos,
                Email = datosPedido.Email,
                EstadoPedido = datosPedido.EstadoPedido,
                FormaPagoId = datosPedido.FormaPagoId,
                PedidoDireccion = datosPedido.PedidoDireccion,
                PedidoFecha = datosPedido.PedidoFecha,
                Telefono = datosPedido.Telefono,
                UsuarioId = usuario,
            };

            var detalle = db.DetallePedidos.Include(d => d.Productos).Include(d => d.Productos.Category).Include(d => d.Productos.Unidades).Where(d => d.PedidoId == id).ToList();

            pedido.Detalle = detalle;

            return View(pedido);
        }

        // GET: Pedidos/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedidos pedidos = await db.Pedidos.FindAsync(id);
            if (pedidos == null)
            {
                return HttpNotFound();
            }
            return View(pedidos);
        }

        // POST: Pedidos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PedidoId,PedidoFecha,UsuarioId,TotalPedido,EstadoPedido,PedidoDireccion")] Pedidos pedidos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pedidos).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(pedidos);
        }

        // GET: Pedidos/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedidos pedidos = await db.Pedidos.FindAsync(id);
            if (pedidos == null)
            {
                return HttpNotFound();
            }
            return View(pedidos);
        }

        // POST: Pedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Pedidos pedidos = await db.Pedidos.FindAsync(id);
            db.Pedidos.Remove(pedidos);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body>

    @Html.Partial("_NavBar")


    <div class="container body-content container my-5 py-5">
        <div class="content">
            <!--Navbar-->
            <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

                <!-- Navbar brand -->
                <span class="navbar-brand">Categorías:</span>

                <!-- Collapse button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Collapsible content -->
                <div class="collapse navbar-collapse" id="basicExampleNav">

                    <!-- Links -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="/">
                                Todo

                                        <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Categories/Categoria?tipo=Combo Bioseguridad">
                                Combo Bioseguridad
                                </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Categories/Categoria?tipo=General">
                                General
                                </a>
                        </li>

                    </ul>
                    <!-- Links -->

                    <form class="form-inline" method="get" action="/Categories/Filter"> 
                        <div class="md-form my-0">
                            <input value="@ViewBag.textoSearch" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="Search" id="Search">
                        </div>
                    </form>
                </div>
                <!-- Collapsible content -->

            </nav>
            <!--/.Navbar-->

            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/fontaw")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ProyectoFinal/Views/Shared/_NavBar.cshtml
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">
        @Html.ActionLink("Krisali", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Inicio", "Index", "Home", null, htmlAttributes: new { @class = "nav-link" })

                </li>
                <li class="nav-item active">
                    @Html.ActionLink("Historial Compras", "Index", "Pedidos", null, htmlAttributes: new { @class = "nav-link" })

                </li>
                @*<li class="nav-item">
            <a class="nav-link" href="#">Link</a>
        </li>*@
                @if (User.IsInRole("admin"))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Mantenimiento
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @Html.ActionLink("Usuarios", "IndexUsers", "Account", null, htmlAttributes: new { @class = "dropdown-item" })
                            <div class="dropdown-divider"></div>
                            @Html.ActionLink("Roles", "IndexRoles", "Account", null, htmlAttributes: new { @class = "dropdown-item" })
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Tienda
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @Html.ActionLink("Categorias", "Index", "Categories", null, htmlAttributes: new { @class = "dropdown-item" })
                            @Html.ActionLink("Unidades", "Index", "Unidades", null, htmlAttributes: new { @class = "dropdown-item" })
                            @Html.ActionLink("Formas de Pago", "Index", "FormaPagoes", null, htmlAttributes: new { @class = "dropdown-item" })
                            <div class="dropdown-divider"></div>
                            @Html.ActionLink("Productos", "Index", "Productos", null, htmlAttributes: new { @class = "dropdown-item" })

                        </div>
                    </li>
                }
                @*<li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>*@
            </ul>

            <div id="carrito" style="padding-left:5px;"></div>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</nav>

<script type="text/javascript">
    $(document).ready(function () {
        var serviceURL = '/Carritoes/_Carrito';

        $.ajax({
            type: "GET",
            url: serviceURL,
            data: param = "",
            dataType: "json",
            error: successFunc
        });

        function successFunc(data) {
            document.getElementById("carrito").innerHTML = data.responseText;
        }
    });
</script>
@*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li></li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>*@

ProyectoFinal/Views/Shared/_RolesVistaLayout.cshtml
@using Microsoft.AspNet.Identity