ProyectoFinal/Models/Carrito.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ProyectoFinal.Models
{
    public class Carrito
    {
        [Key]
        [Display(Name ="ID")]
        public int CarritoId { get; set; }

        [Display(Name = "Usuario ID")]
        public string UsuarioId { get; set; }

        [Display(Name = "Cantidad")]
        public int CarritoCantidad { get; set; }

        [Display(Name = "Fecha")]
        [DataType(DataType.Date)]
        public DateTime FechaAgregado { get; set; }

        [Display(Name = "Producto ID")]
        public int IdProducto { get; set; }
        [ForeignKey("IdProducto")]
        public Productos Producto { get; set; }
    }
}

ProyectoFinal/Controllers/CarritoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoFinal.Context;
using ProyectoFinal.Models;
using Microsoft.AspNet.Identity;
using System.Data.Entity.Migrations;
using ProyectoFinal.Models.ViewModels;
using Microsoft.AspNet.Identity.Owin;

namespace ProyectoFinal.Controllers
{
    public class CarritoesController : Controller
    {
        private ProyectoFinalDbContext db = new ProyectoFinalDbContext();
        private ApplicationUserManager _userManager;

        public CarritoesController()
        {
        }

        public CarritoesController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Carritoes
        public async Task<ActionResult> Index(string msg)
        {
            if (msg != null)
            {
                ViewBag.Mensaje = msg;
            }
            string usuario = null;

            if (User.Identity.IsAuthenticated)
            {
                usuario = User.Identity.GetUserId();
            }
            else
            {
                if (Session["UniqueIdUserAnonimo"] == null)
                {
                    usuario = Guid.NewGuid().ToString();
                    Session["UniqueIdUserAnonimo"] = usuario;
                }
                else
                {
                    usuario = (string)Session["UniqueIdUserAnonimo"];
                }

            }

            //para quitar del carrito los productos agregados por usuarios anonimos que hayan perdido o caducado el tiempo de la sesion 
            //se deberia de crear una condicion que cada verifique la fecha de registro del producto en la carretilla y calcular 24 horas que es el tiempo maximo de una
            //sesion de un usuario anonimo dicho tiempo esta en web.config en el apartado de <system.web> <sessionState timeout="86400"></sessionState>

            var carritoes = db.Carritoes.Include(c => c.Producto).Where(x=>x.UsuarioId == usuario);

            return View(await carritoes.ToListAsync());
        }


        public async Task<ActionResult> Add(DetalleProductoViewModel model,int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var producto = await db.Productos.FindAsync(id);
            if (producto == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            string usuario = null;
            if (User.Identity.IsAuthenticated)
            {
                usuario = User.Identity.GetUserId();
            }
            else
            {
                if (Session["UniqueIdUserAnonimo"] == null)
                {
                    usuario = Guid.NewGuid().ToString();
                    Session["UniqueIdUserAnonimo"] = usuario;
                }
                else
                {
                    usuario = (string)Session["UniqueIdUserAnonimo"];
                }


            }

            var verificar = db.Carritoes.Where(x => x.IdProducto == id && x.UsuarioId == usuario).SingleOrDefault();
            if (producto.ProductStock > 0 && producto.ProductStock >= model.Cantidad)
            {
                if (verificar != null)
                {
                    var addCarrito = new Carrito
                    {
                        CarritoId = verificar.CarritoId,
                        CarritoCantidad = verificar.CarritoCantidad + model.Cantidad,
                        FechaAgregado = DateTime.Now,
                        IdProducto = (int)id,
                        UsuarioId = usuario
                    };
                    db.Set<Carrito>().AddOrUpdate(addCarrito);
                    await db.SaveChangesAsync();
                    //actualizar a cantidad de la carretilla si ya existe un producto agregado
                }
                else
                {
                    var addCarrito = new Carrito
                    {
                        CarritoCantidad = model.Cantidad,
                        FechaAgregado = DateTime.Now,
                        IdProducto = (int)id,
                        UsuarioId = usuario
                    };
                    db.Carritoes.Add(addCarrito);
                    await db.SaveChangesAsync();
                }
                var prod = await db.Productos.FindAsync(id);
                var updateProducto = new Productos
                {
                    IdProducto = prod.IdProducto,
                    CategoryKey = prod.CategoryKey,
                    ProductoImagenes = prod.ProductoImagenes,
                    ProductoTitulo = prod.ProductoTitulo,
                    ProductoPrecio = prod.ProductoPrecio,
                    ProductStock = prod.ProductStock - model.Cantidad,
                    ProdutoDescripcion = prod.ProdutoDescripcion,
                    UnidadesId = prod.UnidadesId
                };
                db.Set<Productos>().AddOrUpdate(updateProducto);
                await db.SaveChangesAsync();
            }
            else
            {
                return RedirectToAction("Index", "Home", new { msg = "Stock Insuficiente" });
            }

            return RedirectToAction("Index", "Home", new { msg = "Producto añadido al carrito" });
        }

        // GET: Carritoes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Carrito carrito = await db.Carritoes.FindAsync(id);
            if (carrito == null)
            {
                return HttpNotFound();
            }
            return View(carrito);
        }
        
        [HttpGet]
        public ActionResult _Carrito()
        {
            string usuario = null;

            if (User.Identity.IsAuthenticated)
            {
                usuario = User.Identity.GetUserId();
            }
            else
            {
                if (Session["UniqueIdUserAnonimo"] == null)
                {
                    usuario = Guid.NewGuid().ToString();
                    Session["UniqueIdUserAnonimo"] = usuario;
                }
                else
                {
                    usuario = (string)Session["UniqueIdUserAnonimo"];
                }

            }
            ViewBag.Cant = db.Carritoes.Where(x => x.UsuarioId == usuario).Count();
            return PartialView();
        }

        // POST: Carritoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<ActionResult> Create(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var producto = await db.Productos.FindAsync(id);
            if(producto == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            string usuario = null;
            if (User.Identity.IsAuthenticated)
            {
                usuario = User.Identity.GetUserId();
            }
            else
            {
                if(Session["UniqueIdUserAnonimo"] == null)
                {
                    usuario = Guid.NewGuid().ToString();
                    Session["UniqueIdUserAnonimo"] = usuario;
                }
                else
                {
                    usuario = (string)Session["UniqueIdUserAnonimo"];
                }
               
                
            }

            var verificar = db.Carritoes.Where(x => x.IdProducto == id &&  x.UsuarioId == usuario).SingleOrDefault();
            if (producto.ProductStock > 0 )
            {
                if (verificar != null)
                {
                    var addCarrito = new Carrito
                    {
                        CarritoId = verificar.CarritoId,
                        CarritoCantidad = verificar.CarritoCantidad + 1,
                        FechaAgregado = DateTime.Now,
                        IdProducto = (int)id,
                        UsuarioId = usuario
                    };
                    db.Set<Carrito>().AddOrUpdate(addCarrito);
                    await db.SaveChangesAsync();
                    //actualizar a cantidad de la carretilla si ya existe un producto agregado
                }
                else
                {
                    var addCarrito = new Carrito
                    {
                        CarritoCantidad = 1,
                        FechaAgregado = DateTime.Now,
                        IdProducto = (int)id,
                        UsuarioId = usuario
                    };
                    db.Carritoes.Add(addCarrito);
                    await db.SaveChangesAsync();
                }
                var prod = await db.Productos.FindAsync(id);
                var updateProducto = new Productos
                {
                    IdProducto = prod.IdProducto,
                    CategoryKey = prod.CategoryKey,
                    ProductoImagenes = prod.ProductoImagenes,
                    ProductoTitulo = prod.ProductoTitulo,
                    ProductoPrecio = prod.ProductoPrecio,
                    ProductStock = prod.ProductStock - 1,

ProyectoFinal/Views/Carritoes/Create.cshtml
@model ProyectoFinal.Models.Carrito

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Carrito</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UsuarioId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UsuarioId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UsuarioId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarritoCantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CarritoCantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CarritoCantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaAgregado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaAgregado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaAgregado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdProducto, "IdProducto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdProducto", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdProducto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProyectoFinal/Views/Carritoes/Delete.cshtml
@model ProyectoFinal.Models.Carrito

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Carrito</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Producto.ProductoTitulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Producto.ProductoTitulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UsuarioId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CarritoCantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarritoCantidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CarritoSubTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarritoSubTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaAgregado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaAgregado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProyectoFinal/Views/Carritoes/Details.cshtml
@model ProyectoFinal.Models.Carrito

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Carrito</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Producto.ProductoTitulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Producto.ProductoTitulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UsuarioId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CarritoCantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarritoCantidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaAgregado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaAgregado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CarritoId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProyectoFinal/Views/Carritoes/Edit.cshtml
@model ProyectoFinal.Models.Carrito

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Carrito</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CarritoId)

        <div class="form-group">
            @Html.LabelFor(model => model.UsuarioId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UsuarioId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UsuarioId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarritoCantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CarritoCantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CarritoCantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaAgregado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaAgregado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaAgregado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdProducto, "IdProducto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdProducto", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdProducto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProyectoFinal/Views/Carritoes/Index.cshtml
@model IEnumerable<ProyectoFinal.Models.Carrito>

@{
    ViewBag.Title = "Carrito";
    System.Data.SqlTypes.SqlMoney Grantotal = 0;
}

<h2>Carrito</h2>
    @if (ViewBag.Mensaje != null)
    {
<div class="alert alert-info">@ViewBag.Mensaje</div>
    }
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Producto.ProductoTitulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CarritoCantidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Producto.ProductoPrecio)
        </th>
        <th>
            Sub Total
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        var cantidad = (Html.DisplayFor(modelItem => item.CarritoCantidad)).ToString();
        var precio = Html.DisplayFor(modelItem => item.Producto.ProductoPrecio).ToString();
        var total = (decimal.Parse(cantidad) * decimal.Parse(precio));
        Grantotal += total;
        <tr>
            <td>
                @using (Html.BeginForm("Delete", "Carritoes", new { id = item.CarritoId }, FormMethod.Post, htmlAttributes: new { style = "display:inline-block;" }))
                {
                    @Html.AntiForgeryToken()
                    <button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Producto.ProductoTitulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarritoCantidad)
            </td>
            <td>
                L @Html.DisplayFor(modelItem => item.Producto.ProductoPrecio)
            </td>
            <td>L @total.ToString()</td>
            <td>
                @using (Html.BeginForm("RemoveOne", "Carritoes", new { id = item.IdProducto }, FormMethod.Post, htmlAttributes: new { style = "display:inline-block;" }))
                {
                    <button type="submit" class="btn btn-danger"><i class="fas fa-minus"></i></button>
                }
                &nbsp; &nbsp; &nbsp; &nbsp;
                @using (Html.BeginForm("AddOne", "Carritoes", new { id = item.IdProducto }, FormMethod.Post, htmlAttributes: new { style = "display:inline-block;" }))
                {
                    <button class="btn btn-success" type="submit"><i class="fas fa-plus"></i></button>
                }
            </td>

        </tr>

    }
</table>
<div class="row">

    <div class="col-lg-7"></div>
    <div class="col-lg-2"> &nbsp; &nbsp;&nbsp; &nbsp;<strong>Total: L @Grantotal</strong></div>
    <div class="col-lg-3">
        @if (Model.Any())
        {
            using (Html.BeginForm("Details", "Pedidos", FormMethod.Post, null))
            {
                <button class="btn btn-black" type="submit">Proceder al pago</button>
            }
        }
    </div>
</div>

ProyectoFinal/Views/Carritoes/_Carrito.cshtml
    @using (Html.BeginForm("Index", "Carritoes",null, FormMethod.Get,null))
    {
    <button type="submit" class="btn btn-primary">
        <i class="fas fa-shopping-cart"></i> &nbsp; Carrito: <span class="badge badge-light">@ViewBag.Cant</span>
    </button>
    }